function M = jacobian_M(in1)
%jacobian_M
%    M = jacobian_M(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    11-Jan-2023 10:02:04

M = reshape([1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0],[4,4]);
